-- Potato Charger forum schema
-- Run this file once in Supabase SQL Editor, or apply it with the Supabase CLI.
-- It deliberately seeds categories only: no placeholder forum threads or users.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_]{3,24}$'),
  display_name text not null check (char_length(trim(display_name)) between 1 and 48),
  bio text not null default '' check (char_length(bio) <= 280),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 2048),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,48}$'),
  name text not null check (char_length(trim(name)) between 2 and 80),
  description text not null check (char_length(trim(description)) between 2 and 180),
  accent text not null default '#f16632' check (accent ~ '^#[0-9A-Fa-f]{6}$'),
  position smallint not null default 0 unique,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_threads (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.forum_categories (id) on delete restrict,
  author_id uuid not null references public.profiles (id) on delete cascade,
  title text not null check (char_length(trim(title)) between 5 and 140),
  body text not null check (char_length(trim(body)) between 1 and 10000),
  reply_count integer not null default 0 check (reply_count >= 0),
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_posts (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.forum_threads (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists forum_threads_category_activity_idx
  on public.forum_threads (category_id, last_activity_at desc);
create index if not exists forum_threads_last_activity_idx
  on public.forum_threads (last_activity_at desc);
create index if not exists forum_posts_thread_created_idx
  on public.forum_posts (thread_id, created_at asc);

-- Keep client-supplied profile and forum timestamps honest.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists forum_threads_set_updated_at on public.forum_threads;
create trigger forum_threads_set_updated_at
before update on public.forum_threads
for each row execute function public.set_updated_at();

drop trigger if exists forum_posts_set_updated_at on public.forum_posts;
create trigger forum_posts_set_updated_at
before update on public.forum_posts
for each row execute function public.set_updated_at();

-- Every auth user receives a public profile. The UUID suffix makes usernames
-- collision-resistant while still keeping them safe to expose in the UI.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cleaned_name text;
begin
  cleaned_name := lower(regexp_replace(coalesce(split_part(new.email, '@', 1), 'player'), '[^a-z0-9_]+', '_', 'g'));
  cleaned_name := trim(both '_' from cleaned_name);
  if char_length(cleaned_name) < 3 then
    cleaned_name := 'player';
  end if;

  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    left(cleaned_name, 17) || '_' || left(replace(new.id::text, '-', ''), 6),
    coalesce(nullif(split_part(new.email, '@', 1), ''), 'Potato player')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Make profiles for existing auth users if this migration is added later.
insert into public.profiles (id, username, display_name)
select
  users.id,
  'player_' || left(replace(users.id::text, '-', ''), 6),
  coalesce(nullif(split_part(users.email, '@', 1), ''), 'Potato player')
from auth.users as users
on conflict (id) do nothing;

-- Count replies and keep the thread activity timestamp in sync. Clients never
-- write either field directly.
create or replace function public.sync_thread_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_thread uuid;
begin
  affected_thread := coalesce(new.thread_id, old.thread_id);

  update public.forum_threads as thread
  set
    reply_count = (select count(*) from public.forum_posts where thread_id = affected_thread),
    last_activity_at = greatest(
      thread.created_at,
      coalesce((select max(created_at) from public.forum_posts where thread_id = affected_thread), thread.created_at)
    )
  where thread.id = affected_thread;

  return coalesce(new, old);
end;
$$;

drop trigger if exists forum_posts_sync_thread_activity on public.forum_posts;
create trigger forum_posts_sync_thread_activity
after insert or delete on public.forum_posts
for each row execute function public.sync_thread_activity();

insert into public.forum_categories (slug, name, description, accent, position)
values
  ('getting-started', 'Getting Started & PC Builds', 'Introductions, parts, setup advice, and sensible starting points.', '#f16632', 1),
  ('game-optimizations', 'Game Optimizations', 'Settings, FPS targets, troubleshooting, and realistic game plans.', '#7da522', 2),
  ('configs-patches-fixes', 'Configs, Patches & Fixes', 'Community-tested configs and compatibility fixes.', '#637dc0', 3),
  ('budget-upgrades', 'Budget Hardware Upgrades', 'Practical upgrades for aging systems and tight budgets.', '#c58a43', 4),
  ('lighter-apps', 'Lighter Apps & Windows Efficiency', 'Better daily apps and ways to reduce background bloat.', '#9d6fb0', 5),
  ('help-desk', 'Help Desk', 'Ask for peer support when a game or system refuses to cooperate.', '#628e8d', 6)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  accent = excluded.accent,
  position = excluded.position;

alter table public.profiles enable row level security;
alter table public.forum_categories enable row level security;
alter table public.forum_threads enable row level security;
alter table public.forum_posts enable row level security;

drop policy if exists "Profiles are visible to everyone" on public.profiles;
create policy "Profiles are visible to everyone"
on public.profiles for select
using (true);

drop policy if exists "Members can update their own profile" on public.profiles;
create policy "Members can update their own profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Categories are visible to everyone" on public.forum_categories;
create policy "Categories are visible to everyone"
on public.forum_categories for select
using (true);

drop policy if exists "Threads are visible to everyone" on public.forum_threads;
create policy "Threads are visible to everyone"
on public.forum_threads for select
using (true);

drop policy if exists "Members can create their own threads" on public.forum_threads;
create policy "Members can create their own threads"
on public.forum_threads for insert to authenticated
with check (auth.uid() = author_id);

drop policy if exists "Members can edit their own threads" on public.forum_threads;
create policy "Members can edit their own threads"
on public.forum_threads for update to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

drop policy if exists "Members can delete their own threads" on public.forum_threads;
create policy "Members can delete their own threads"
on public.forum_threads for delete to authenticated
using (auth.uid() = author_id);

drop policy if exists "Posts are visible to everyone" on public.forum_posts;
create policy "Posts are visible to everyone"
on public.forum_posts for select
using (true);

drop policy if exists "Members can create their own posts" on public.forum_posts;
create policy "Members can create their own posts"
on public.forum_posts for insert to authenticated
with check (auth.uid() = author_id);

drop policy if exists "Members can edit their own posts" on public.forum_posts;
create policy "Members can edit their own posts"
on public.forum_posts for update to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

drop policy if exists "Members can delete their own posts" on public.forum_posts;
create policy "Members can delete their own posts"
on public.forum_posts for delete to authenticated
using (auth.uid() = author_id);

-- Explicit grants keep the browser client limited to the anonymous/public API.
revoke all on public.profiles, public.forum_categories, public.forum_threads, public.forum_posts from anon, authenticated;
grant select on public.profiles, public.forum_categories, public.forum_threads, public.forum_posts to anon;
grant select on public.profiles, public.forum_categories, public.forum_threads, public.forum_posts to authenticated;
grant update (username, display_name, bio, avatar_url) on public.profiles to authenticated;
grant insert, delete on public.forum_threads, public.forum_posts to authenticated;
grant update (category_id, title, body) on public.forum_threads to authenticated;
grant update (body) on public.forum_posts to authenticated;

-- Optional: enable live refreshes after confirming your project uses Realtime.
-- alter publication supabase_realtime add table public.forum_threads, public.forum_posts;
